### ISSUE TITLE
Square root function does not work(

### ISSUE THREAD

**Issue by kod3ch** [kod3ch/multicalc#1]
Now You can't calculate square root of some number because of this _s**t_:
`btn_sqrt = Button(root, text="√x", padx=45, pady=20, command=sqrt, state=DISABLED)`
`def sqrt():
    num = float(e.get())
    e.delete(0, END)
    e.insert(0, sqrt(num))`
![image](https://user-images.githubusercontent.com/18100538/85864056-4e19ad00-b7c4-11ea-9db8-e5171f5c34ed.png)
IDK why this argument is __unexpected__ xd

**Comment by pErsten** [comment]
lol, just use pow()

**Comment by kod3ch** [comment]
@pErsten thx a lot <3
I just forgot that there is such an elementary solution
`e.insert(0, pow(num, 0.5))`
XD
